# Generated by Django 5.1.4 on 2024-12-05 16:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetrack',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pricetrack',
            name='last_checked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricetrack',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pricetrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricetrack',
            name='progress',
            field=models.CharField(choices=[('tracking', 'Tracking'), ('complete', 'Complete'), ('error', 'Error')], default='tracking', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricetrack',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
