# Generated by Django 5.1.4 on 2024-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_pricetrack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetrack',
            name='url_link',
            field=models.URLField(max_length=1000),
        ),
    ]
